# Generated by Django 4.1.7 on 2023-05-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
